# .github/workflows/ci.yml
name: iOS CI/CD

on:
  push:
    branches:
      - main # Trigger on push to main branch (or any branch you prefer)
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: macos-latest # This specifies that the job should run on a macOS runner
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Xcode
      - name: Set up Xcode
        uses: maxheld83/setup-xcode@v1
        with:
          xcode-version: '14.1' # Specify the desired version of Xcode

     

      # Step 4: Build the app
      - name: Build the app
        run: |
          xcodebuild clean build -project GithubActionsDemoProject.xcodeproj -scheme GithubActionsDemoProject -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 18.1'

      