name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Xcode
      - name: Set up Xcode
        run: xcode-select -p

  
      # Build the project
      - name: Build
        run: xcodebuild -project GithubActionsDemoProject.xcodeproj -scheme GithubActionsDemoProject -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' clean build

  