name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Xcode
      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app


      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.P12_CER_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_KEY_BASE64 }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db


  
      # Step 5: Build the app with automatic signing
      - name: Build
        run: |
          xcodebuild clean build \
          -project GithubActionsDemoProject.xcodeproj \
          -scheme GithubActionsDemoProject \
          -sdk iphoneos \
          -configuration Release 

    #end jobs